@Licoreria.WebAPI_HostAddress = http://localhost:5190

### RFC 7807 - 404
GET {{Licoreria.WebAPI_HostAddress}}/api/test-error/not-found
Accept: application/json

### RFC 7807 - 400
GET {{Licoreria.WebAPI_HostAddress}}/api/test-error/bad-request
Accept: application/json

### RFC 7807 - 500
GET {{Licoreria.WebAPI_HostAddress}}/api/test-error/server-error
Accept: application/json

###
